import type { Metadata } from "next";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Montserrat, Italiana } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["200"],
});

const italiana = Italiana({
  variable: "--font-italiana",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Jennifer Tabbert Photography",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable}  ${italiana.variable} antialiased `}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
